campingbike/urls.py
from django.conf.urls import url

from . import views

app_name = 'campingbike'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^familiar', views.familiar, name='familiar'),
    url(r'^parelles', views.parelles, name='parelles'),
    url(r'^endurance', views.endurance, name='endurance'),
    url(r'^maps$', views.maps, name='maps'),
    url(r'^experiencies', views.experiencies, name='experiencies'),
    url(r'^lloguer', views.lloguer, name='lloguer'),
    url(r'^politica', views.politica, name='politica'),
    # Urls per M04
    url(r'^descarrega', views.descarrega, name='descarrega'),
    url(r'^xml', views.xml,name="xml"),
    url(r'^json', views.json,name="json"),
    url(r'^csv', views.export,name="csv"),

]

campingf/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('campingbike.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n'))
]
if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        url(r'^rosetta/', include('rosetta.urls'))
    ]

campingbike/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Ruta(models.Model):
    nom = models.CharField(max_length=20)
    def __str__(self):
        return self.nom

class Comentari(models.Model):
    TIPUS = (
        ('F', 'Familiar'),
        ('P', 'Parelles'),
        ('E', 'Endurance'),
    )
    comentari = models.ForeignKey(Ruta, on_delete=models.CASCADE)
    tipus = models.CharField(max_length=1,choices=TIPUS,null=True,blank=True)
    temps = models.CharField(max_length=10)
    km = models.IntegerField()
    link = models.CharField(max_length=200)
    imatge = models.CharField(max_length=200)
    opinio = models.CharField(max_length=300)

    def __str__(self):
        return self.tipus

campingbike/views.py
from django.shortcuts import render
from .models import Comentari
import folium
# Create your views here.
def index(request):
    return render(request,'campingbike/index.html')

def familiar(request):
    rutes = Comentari.objects.filter(tipus='F')
    return render(request,'campingbike/familiar.html',{'Rutes':rutes})

def parelles(request):
    rutes = Comentari.objects.filter(tipus='P')
    return render(request,'campingbike/parelles.html',{'Rutes':rutes})

def endurance(request):
    rutes = Comentari.objects.filter(tipus='E')
    return render(request,'campingbike/endurance.html',{'Rutes':rutes})

def get_endurance(request):
    rutes = Comentari.objects.filter(tipus='E').values('tipus', 'temps', 'km', 'link', 'imatge', 'opinio')
    rutes_list = list(rutes)
    return JsonResponse(rutes_list, safe= False)

def maps(request):
    return render(request,'campingbike/maps.html')

def experiencies(request):
    return render(request,'campingbike/experiencies.html')

def lloguer(request):
    return render(request,'campingbike/lloguer.html')

def politica(request):
    return render(request,'campingbike/politica.html')

# Vistes per M04

from django.http import JsonResponse,HttpResponse
from django.core import serializers

def xml(request):
    data = Comentari.objects.all()
    data = serializers.serialize('xml',data)
    return HttpResponse(data, content_type="application/xml")

def json(request):
    data = Comentari.objects.all().values('tipus', 'temps', 'km', 'link', 'imatge', 'opinio')
    rutes_list = list(data)
    return JsonResponse(rutes_list, safe= False)

from .resources import RutaResource

def export(request):
    ruta_resource = RutaResource()
    dataset = ruta_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="rutes.csv"'
    return response

def descarrega(request):
    return render(request,'campingbike/descarrega.html')

campingbike/templates/campingbike/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Camping bike Vell Emporda</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
    <!--<link rel="stylesheet" src="{% static 'campingbike/cookies/purecookie.css' %}"/>-->
    <link src="{% static 'campingbike/css/base.css' %}"/>

    {% block head %}
    {% endblock %}
</head>
<body>
    <!--Start of navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light position-relative">
        <a href="{% url 'campingbike:index' %}"><img class="navbar-brand" height="50px" src="{% static 'campingbike/logo.png' %}"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans "Rutes" %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'campingbike:familiar' %}">{% trans "Familiar" %}</a>
                        <a class="dropdown-item" href="{% url 'campingbike:parelles' %}">{% trans "Parelles" %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'campingbike:endurance' %}">Endurance</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'campingbike:lloguer' %}">{% trans "Servei lloguer" %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="{% url 'campingbike:experiencies' %}" tabindex="-1" aria-disabled="true">
                        {% trans "Experiencies" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://bookings.masterasp.com/?estab=365&lang=ca" tabindex="-1" aria-disabled="true">{% trans "Reserva" %}</a>
                </li>
            </ul>
            <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                <input name="next" type="hidden" value="{{ redirect_to }}" />
                <select name="language">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for language in languages %}pyt
                        <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                            {{ language.name_local }} ({{ language.code }})
                        </option>
                    {% endfor %}
                </select>
                <input type="submit" value="Go" />
            </form>
            <ul class="navbar-nav my-2 my-lg-0">
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'campingbike:maps' %}" tabindex="-1" aria-disabled="true">{% trans "Mapa(Rutes)" %}</a>
                </li>
            </ul>
        </div>

    </nav>
    <!--End of navbar-->

    {% block content %}
    {% endblock %}
    
    <!-- Footer -->
    <div class="container-fluid bg-primary py-1">
    <div class="container">
      <div class="row py-4">
        <div class="col-md-9">
            <a href="http://www.vellemporda.com"><p class="text-white mt-3 display-5">Camping Vell Emporda</p></a>
            <a href="{% url 'campingbike:politica' %}"><p class="text-white mt-3 display-5">Politica de privacitat</p></a>
        </div>
        <div class="col-md-3">
          <div class="d-inline-block">
            <div class="bg-circle-outline d-inline-block">
              <a href="https://www.facebook.com/" class="text-white"><i class="fab fa-facebook"></i>
		</a>
            </div>

            <div class="bg-circle-outline d-inline-block">
              <a href="https://www.instagram.com/campingbikevellemporda/" class="text-white">
                <i class="fab fa-instagram"></i></a>
            </div>

            <div class="bg-circle-outline d-inline-block">
              <a href="mailto:vellemporda@vellemporda.com" target="_top">
                <i class="text-white fas fa-envelope-square"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    <!--End of footer -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" ></script>
    <!--<script src="{% static 'campingbike/cookies/purecookie.js' %}"></script>-->
    <script src="{% static 'campingbike/js/base.js' %}"></script>

    {% block js%}
    {% endblock %}
</body>
</html>

campingbike/templates/campingbike/descarrega.html
{% extends 'campingbike/base.html' %}
{% load i18n %}
{% block content %}
<div class="container">
    <a href="{% url 'campingbike:xml' %}">XML</a><br>
    <a href="{% url 'campingbike:json' %}">JSON</a><br>
    <a href="{% url 'campingbike:csv' %}">CSV</a>
</div>
{% endblock %}

campingbike/templates/campingbike/endurance.html
{% extends 'campingbike/base.html' %}
{% load static %}
{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script>L_PREFER_CANVAS=false; L_NO_TOUCH=false; L_DISABLE_3D=false;</script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css"/>


    <meta name="viewport" content="width=device-width,
        initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'campingbike/css/endurance.css' %}">
{% endblock %}
{% block content %}
    <h2>Coll de banyuls</h2>
    <div class="folium-map" id="map_6be92f8b4bd54b78905cd14785fa6164" ></div>
    <div id="mapContainer" class="d-block"></div>
    <div class="row justify-content-end  pt-3">
        <img id="altimetria"class=" " src="{% static 'campingbike/Rutaverda.png' %}"><br>
    </div>

    <h2 id="" class="">St. Pere de Rodes</h2>
    <div id="mapContainer2" ></div>
    <div class="row justify-content-end  pt-3">
        <img id="altimetria2"class=" " src="{% static 'campingbike/Rutaverda.png' %}"><br>
    </div>
    <div class="comentaris d-block pt-5">
    <h3 class="pb-3">Opinions</h3>

        {% for ruta in Rutes %}
        <div class="row p-2">
            <img src="{{ruta.imatge}}" class="col-lg-5 col-md-6" width="100%"height="100%">
            <div class="col-md-6 col-lg-7 p-3">
                <p>Ruta: {{ruta.comentari}}</p>
                <p>Distancia: {{ruta.km}} km. Temps: {{ruta.temps}}</p>
                <p>{{ruta.opinio}}</p>
                <a  href="{{ruta.link}}">Link a la ruta</a>
            </div>
        </div>
        {% endfor %}
    </div>

<script src="{% static 'campingbike/js/endurance.js' %}"></script>
{% endblock %}

campingbike/templates/campingbike/experiencies.html
{% extends 'campingbike/base.html' %}
{% load i18n %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'campingbike/css/experiencies.css' %}">
{% endblock %}
{% block content %}
   <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'campingbike/bicis-sortida.jpg' %}"></div>
    <div class="container m-5">
      <h2 class="header">{% trans "Rutes" %}</h2>
      <p class="grey-text text-darken-3 lighten-3">{% trans "En el camping oferim les rutes més emblematiques de la nostre zona." %}</p>
    </div>

  <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'campingbike/glamping.jpg' %}"></div>

    <div class="container m-5 ">
      <h2 class="header">Cycling tour</h2>
      <p class="grey-text text-darken-3 lighten-3">{% trans "Colaborem amb cycling tours per fer rutes" %}</p>
    </div>

  <div class="parallax-window" data-parallax="scroll" data-image-src="https://static.joandjudy.com/media/image/4e/c8/62/JJ_Wallpaper_Maerz_2019KMyNyRsW2UcZr.jpg"></div>

    <div class="container m-5">
      <h2 class="header">Fiets fun</h2>
      <p>{% trans "Fiets fun fa rutes amb tracking" %}</p>
    </div>

    <div class="parallax-window" data-parallax="scroll" data-image-src="{% static 'campingbike/fiets.jpg' %}"></div>

      <div class="container">
          <div class="row mt-5">
                <div class="col-6 col-lg-4">

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/bicis-linea.jpg' %}" data-width="1536" data-height="2304">
                            <img  class="img-fluid" src="{% static 'campingbike/bicis-linea.jpg' %}">
                        </a>
                    </figure>

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/bicis.jpg' %}" data-width="1279" data-height="853">
                            <img class="img-fluid lazy" src="{% static 'campingbike/bicis.jpg' %}">
                        </a>
                    </figure>

                </div>
                <div class="col-6 col-lg-4">

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/bicis-sortida.jpg' %}" data-width="1279" data-height="719">
                            <img class="img-fluid lazy" src="{% static 'campingbike/bicis-sortida.jpg' %}">
                        </a>
                    </figure>

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/carretera-tenda.jpg' %}" data-width="1279" data-height="853">
                            <img class="img-fluid lazy" src="{% static 'campingbike/carretera-tenda.jpg' %}">
                        </a>
                    </figure>

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/cycle.jpg' %}" data-width="1020" data-height="858">
                            <img class="img-fluid lazy" src="{% static 'campingbike/cycle.jpg' %}">
                        </a>
                    </figure>

                </div>
                <div class="col-6 col-lg-4 d-none d-lg-block">

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/spining.jpg' %}" data-width="1279" data-height="870">
                            <img class="img-fluid lazy" src="{% static 'campingbike/spining.jpg' %}">
                        </a>
                    </figure>

                    <figure>
                        <a class="d-block mb-4" data-fancybox="images" href="{% static 'campingbike/carretera-cadira.jpg' %}" data-width="1519" data-height="2279">
                            <img class="img-fluid lazy" src="{% static 'campingbike/carretera-cadira.jpg' %}">
                        </a>
                    </figure>
                </div>
            </div>
      </div>
{% endblock %}
{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>
<script src="{% static 'campingbike/parallax/parallax.js' %}"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery.lazy/1.7.9/jquery.lazy.plugins.min.js"></script>
<script src="{% static 'campingbike/js/experiencies.js' %}"></script>

{% endblock %}

campingbike/templates/campingbike/familiar.html
{% extends 'campingbike/base.html' %}
{% load static %}
{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script>L_PREFER_CANVAS=false; L_NO_TOUCH=false; L_DISABLE_3D=false;</script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css"/>


    <meta name="viewport" content="width=device-width,
        initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'campingbike/css/endurance.css' %}">
{% endblock %}
{% block content %}
    <h2>Sant quirze de colera</h2>
    <div class="folium-map" id="map_6be92f8b4bd54b78905cd14785fa6164" ></div>
    <div id="mapContainer" class="d-block"></div>
    <h3 class="pt-5 pl-2">Opinions</h3>
    <div class="comentaris d-block pt-1">

    </div>

<script src="{% static 'campingbike/js/familiar.js' %}"></script>
{% endblock %}

campingbike/templates/campingbike/index.html
{% extends 'campingbike/base.html' %}
{% load i18n %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/imagehover.css/1.0/css/imagehover.min.css">
<link rel="stylesheet" href="{% static 'InContent-master/css/sass-compiled.css'%}">
<link rel="stylesheet" href="{% static 'campingbike/css/index.css' %}">

{% endblock %}

{% block content %}
<div class="bxslider p-3">
    <div><img src="{% static 'campingbike/cycle.jpg' %}" title=""></div>
    <div><img src="{% static 'campingbike/bicis.jpg' %}" title=""></div>
    <div><img src="{% static 'campingbike/carretera-tenda.jpg' %}" title=""></div>
</div>
<div class="container p-3 ">

  <div class="row pb-5">
    <ul class="ch-grid">

      <li>
          <div class="ch-item ch-img-1">
              <div class="ch-info">
                  <a href="{% url 'campingbike:familiar' %}"><h3>{% trans "Familiar" %}</h3></a>
                  <p>{% trans "Pensades perque hi vagin nens" %}</p>
              </div>
          </div>
      </li>

      <li>
          <div class="ch-item ch-img-2">
              <div class="ch-info">
                  <a href="{% url 'campingbike:parelles' %}"><h3>{% trans "Parelles" %}</h3></a>
                  <p></p>
              </div>
          </div>
      </li>
      <li>
          <div class="ch-item ch-img-3">
              <div class="ch-info">
                  <a href="{% url 'campingbike:endurance' %}"><h3>Endurance</h3></a>
                  <p>{% trans "Les rutes més exigents" %}</p>
              </div>
          </div>
      </li>
    </ul>
  </div>
    <h2>{% trans "Altres opcions" %}</h2>
    <div class="bxslider">
        <div><img src="{% static 'campingbike/visit/1.jpg' %}" style="width:1400px;" title="Peralada, Girona, Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/2.jpg' %}" style="width:1400px;" title="El Port de la Selva (Alt Emporda), Girona, Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/4.jpg' %}" style="width:1400px;" title="Platja de Port Bo (Palafrugell, Baix Emporda), Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/5.jpg' %}" style="width:1400px;" title="Cap de Bou (Banyoles, Pla de l'Estany), Girona, Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/6.jpg' %}" style="width:1400px;" title="Estany de Banyoles, Girona, Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/7.jpg' %}" style="width:1400px;" title="Cadaqués (Cadaqués, Alt Emporda), Girona, Catalonia"></div>
        <div><img src="{% static 'campingbike/visit/9.jpg' %}" style="width:1400px;" title="Aigua Xelida (Palafrugell, Baix Emporda), Girona, Catalonia"></div>


    </div>
</div>

<style>

.ch-img-1 {
	background: url({% static 'campingbike/bicis-sortida.jpg' %});
	background-repeat: no-repeat;
	background-size: 220px 220px;
}

.ch-img-2 {
	background-image: url({% static 'campingbike/couple.jpg' %});
	background-repeat: no-repeat;
	background-size: 220px 220px;
}

.ch-img-3 {
	background-image: url({% static 'campingbike/orbea.jpg' %});
	background-repeat: no-repeat;
	background-size: 220px 220px;
}
</style>
{% endblock %}
{% block js %}
<script src="{% static 'InContent-master/libs/modernizr.js' %}"></script>
<script src="{% static 'node_modules/bxslider/dist/jquery.bxslider.min.js' %}"></script>
<script src="{% static 'campingbike/js/index.js' %}"></script>
<script>

</script>

{% endblock %}

campingbike/templates/campingbike/lloguer.html
{% extends 'campingbike/base.html' %}
{% load i18n %}
{% load static %}
{% block head %}

{% endblock %}
{% block content %}
<div class="container">
    <h2>{% trans "Lloguer de bicicletes" %}</h2>
    <div class="row">
        <img src="https://contents.mediadecathlon.com/p1276519/k$13d043f6eb2db637f37478db517dbb67/sq/BICICLETA+DE+MONTA+A+ROCKRIDER+ST+100+27+5+GRIS.webp?f=550x550" alt="" class="col-6" width="100%" height="100%">
        <div class="col-6 align-middle d-flex justify-content-center align-items-center" >
            <h3>{% trans "BTT - 12€/dia" %}</h3>
        </div>
    </div>
    <div class="row">
        <img src="https://contents.mediadecathlon.com/p1278167/k$1d45c4166cbefcbd8c4bbf9c94ff06b8/sq/BICICLETA+POLIVALENTE+RIVERSIDE+120+GRIS.webp?f=550x550" alt="" class="col-6" width="100%" height="100%">
        <div class="col-6 align-middle d-flex justify-content-center align-items-center ">
            <h3>{% trans "Passeig - 10€/dia" %}</h3>
        </div>
    </div>
</div>
{% endblock %}

campingbike/templates/campingbike/maps.html
{% extends 'campingbike/base.html' %}
{% load static %}
{% block head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
    <script>L_PREFER_CANVAS=false; L_NO_TOUCH=false; L_DISABLE_3D=false;</script>
    <script src="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.js"></script>
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.4.0/dist/leaflet.css"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Leaflet.awesome-markers/2.0.2/leaflet.awesome-markers.css"/>
    <link rel="stylesheet" href="https://rawcdn.githack.com/python-visualization/folium/master/folium/templates/leaflet.awesome.rotate.css"/>
    <style>html, body {width: 100%;height: 100%;margin: 0;padding: 0;}</style>
    <style>#map {position:absolute;top:0;bottom:0;right:0;left:0;}</style>
    
    <meta name="viewport" content="width=device-width,
        initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'campingbike/css/maps.css' %}">
{% endblock %}
{% block content %}
    <div class="folium-map pb-4" id="map_6be92f8b4bd54b78905cd14785fa6164" ></div>
<br>
<br>


{% endblock %}
{% block js %}


    <script src="{% static 'campingbike/js/maps.js' %}"></script>
{% endblock %}